version: '3'
services:
  zookeeper:
    image: public.ecr.aws/bitnami/zookeeper:3.8.1
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka-1:
    image: public.ecr.aws/bitnami/kafka:3.5.1
    container_name: kafka-1
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka-1-data:/bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper

  kafka-2:
    image: public.ecr.aws/bitnami/kafka:3.5.1
    container_name: kafka-2
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - kafka-2-data:/bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper

  kafka-3:
    image: public.ecr.aws/bitnami/kafka:3.5.1
    container_name: kafka-3
    restart: always
    ports:
      - "9094:9094"
    volumes:
      - kafka-3-data:/bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: application
      MYSQL_PASSWORD: application
      MYSQL_DATABASE: hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

networks:
  default:
    driver: bridge
